# Generated by Django 3.2.23 on 2024-01-14 07:49

from django.db import migrations, models

class Migration(migrations.Migration):

   dependencies = [
       ('Recipe_App', '0001_initial'),
   ]

   operations = [
       migrations.AlterField(
           model_name='recipe',
           name='image_data',
           field=models.BinaryField(blank=True, null=True),
       ),
   ]
