# Generated by Django 3.2.23 on 2024-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0002_alter_recipe_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
