# Generated by Django 5.0.1 on 2024-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0003_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
