# Generated by Django 3.2.23 on 2024-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0003_recipe_image_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_format',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
