# Generated by Django 4.2.7 on 2023-12-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0004_subject_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('date_of_creation', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_App.student')),
            ],
        ),
    ]
