# Generated by Django 5.0.1 on 2024-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0004_recipe_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
    ]
