# Generated by Django 5.0.1 on 2024-01-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0006_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='report_card',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='report_card',
        ),
        migrations.DeleteModel(
            name='Student_id',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
